export interface Master {
  firstName: string;
  lastName: string;
  club: string;
  grade: number; // 1–6 = highest achieved DAN
}

export const MASTERS: Master[] = [
  // ─── 1 DAN ───────────────────────────────────────────────────────────────
  { firstName: 'Ghassan', lastName: 'Abdullah', club: 'IMC', grade: 1 },
  { firstName: 'Antonio', lastName: 'Andersson', club: 'Göteborg', grade: 1 },
  { firstName: 'David', lastName: 'Anevski', club: 'FOX Malmö', grade: 1 },
  { firstName: 'Jonas', lastName: 'Appelgren', club: 'FOX Malmö', grade: 1 },
  { firstName: 'Mikael', lastName: 'Baaz', club: 'IMC', grade: 1 },
  { firstName: 'Magnus', lastName: 'Bergström', club: 'Göteborg', grade: 1 },
  { firstName: 'Tony', lastName: 'Berntsson', club: 'Gbg Kick- & Thai', grade: 1 },
  { firstName: 'Anders', lastName: 'Blom', club: 'Slagskeppet', grade: 1 },
  { firstName: 'Robert', lastName: 'Brandin', club: 'Göteborg', grade: 1 },
  { firstName: 'Daniel', lastName: 'Carrasco', club: 'FOX Malmö', grade: 1 },
  { firstName: 'Fransisco', lastName: 'Carrazana', club: 'Jönköping Kick- & Boxningsklubb', grade: 1 },
  { firstName: 'Marcus', lastName: 'Dahl', club: 'FOX Malmö', grade: 1 },
  { firstName: 'Caroline', lastName: 'Ek', club: 'Kalvhagen', grade: 1 },
  { firstName: 'Niclas', lastName: 'Eriksson', club: 'IMC', grade: 1 },
  { firstName: 'Anders', lastName: 'Gustafsson', club: 'Jönköping Kick- & Boxningsklubb', grade: 1 },
  { firstName: 'Chrstian', lastName: 'Görloff', club: 'FOX Malmö', grade: 1 },
  { firstName: 'Fredrik', lastName: 'Hermansson', club: 'Kungsbacka Kampsportscenter', grade: 1 },
  { firstName: 'Fredrik', lastName: 'Hjelm', club: 'FOX Malmö', grade: 1 },
  { firstName: 'Markus', lastName: 'Hjortheimer', club: 'Göteborg', grade: 1 },
  { firstName: 'Lai', lastName: 'Jagne', club: 'FOX Malmö', grade: 1 },
  { firstName: 'Jan-Erik', lastName: 'Johansson', club: 'Partille', grade: 1 },
  { firstName: 'Marcus', lastName: 'Johansson', club: 'Kalvhagen', grade: 1 },
  { firstName: 'Robert', lastName: 'Johansson', club: 'Enköping', grade: 1 },
  { firstName: 'Peter', lastName: 'Jönsson', club: 'Göteborg', grade: 1 },
  { firstName: 'Jonas', lastName: 'Kalderstam', club: 'Fighting Spirit Kickboxningsklubb', grade: 1 },
  { firstName: 'Ari', lastName: 'Kangas', club: 'Finland', grade: 1 },
  { firstName: 'Aje', lastName: 'Kindmark', club: 'FOX Malmö', grade: 1 },
  { firstName: 'Paul', lastName: 'Klinkert', club: 'FOX Malmö', grade: 1 },
  { firstName: 'Igor', lastName: 'Kourrinoi', club: 'Stockholm', grade: 1 },
  { firstName: 'Rikard', lastName: 'Lauritzen', club: 'Gbg Kick- & Thai', grade: 1 },
  { firstName: 'Danny', lastName: 'Lindgren', club: '', grade: 1 },
  { firstName: 'Morgan', lastName: 'Lundkvist', club: 'Helsingborg', grade: 1 },
  { firstName: 'Andreas', lastName: 'Lundqvist', club: 'Jönköping Kick- & Boxningsklubb', grade: 1 },
  { firstName: 'Mike', lastName: 'Molander', club: 'Lund', grade: 1 },
  { firstName: 'Johan', lastName: 'Molinder', club: 'Eskilstuna', grade: 1 },
  { firstName: 'Kim', lastName: 'Möller', club: 'Helsingborg', grade: 1 },
  { firstName: 'Patrik', lastName: 'Nilsson', club: 'Göteborg', grade: 1 },
  { firstName: 'Juma', lastName: "N'tuve", club: 'IMC', grade: 1 },
  { firstName: 'Lisa', lastName: 'Palme', club: 'Kalvhagen', grade: 1 },
  { firstName: 'Lars', lastName: 'Peussa', club: 'IMC', grade: 1 },
  { firstName: 'Håkan', lastName: 'Pihl', club: 'Lund', grade: 1 },
  { firstName: 'David', lastName: 'Plepel', club: 'FOX Malmö', grade: 1 },
  { firstName: 'Christos', lastName: 'Polizonis', club: 'FOX Malmö', grade: 1 },
  { firstName: 'Ola', lastName: 'Pukki', club: 'Jönköping Kick- & Boxningsklubb', grade: 1 },
  { firstName: 'Fredrik', lastName: 'Scheuer', club: 'Lund', grade: 1 },
  { firstName: 'Glenn', lastName: 'Skogh', club: 'Jokkmokk', grade: 1 },
  { firstName: 'Tihomir', lastName: 'Trogrlic', club: 'IMC', grade: 1 },
  { firstName: 'Jonny', lastName: 'Trägårdh', club: 'IMC', grade: 1 },
  { firstName: 'Carl-Oskar', lastName: 'Willanen', club: 'Jönköping Kick- & Boxningsklubb', grade: 1 },
  { firstName: 'Stefan', lastName: 'Zachrisson', club: 'Fox Fagersta Kickboxningsklubb', grade: 1 },
  { firstName: 'Göran', lastName: 'Östman', club: 'Eskilstuna', grade: 1 },
  { firstName: 'Juan-Pablo', lastName: 'Pizarro', club: 'Ironman 424', grade: 1 },
  { firstName: 'Emil', lastName: 'Hossen', club: 'Helsingborgs Muay Thai', grade: 1 },
  { firstName: 'Jonas', lastName: 'Grönhage', club: 'Jönköping Kick- & Boxningsklubb', grade: 1 },
  { firstName: 'Adnan', lastName: 'Mujkanovic', club: 'Göteborgs Kickboxing', grade: 1 },
  { firstName: 'Olof', lastName: 'Huldfeldt', club: 'Ironman Majorna', grade: 1 },
  { firstName: 'Ida', lastName: 'Sihvonen', club: 'Göteborgs Kickboxing', grade: 1 },
  { firstName: 'Oscar', lastName: 'Salazar Aros', club: 'Fighting Spirit Malmö', grade: 1 },
  { firstName: 'Douglas', lastName: 'Franzén', club: 'West Coast Kickboxing', grade: 1 },
  { firstName: 'Sebastian', lastName: 'Grahn', club: 'Jönköping Kick- & Boxningsklubb', grade: 1 },
  { firstName: 'Johan', lastName: 'Abrahamsson', club: 'Göteborgs Kickboxing', grade: 1 },
  { firstName: 'Joakim', lastName: 'Wåhlstrand', club: 'Göteborgs Kickboxing', grade: 1 },
  { firstName: 'Nima', lastName: 'Tahvilzade', club: 'Göteborgs Kickboxing', grade: 1 },
  { firstName: 'Olof', lastName: 'Reichenberg', club: 'Göteborgs Kickboxing', grade: 1 },
  { firstName: 'Oscar', lastName: 'Andersson', club: 'Göteborgs Kickboxing', grade: 1 },
  { firstName: 'Vincent', lastName: 'Collan', club: 'Ironman Majorna', grade: 1 },
  { firstName: 'Jesper', lastName: 'Rosenberg', club: 'West Coast Kickboxing', grade: 1 },
  { firstName: 'Joakim', lastName: 'Nilsson', club: 'West Coast Kickboxing', grade: 1 },
  { firstName: 'Nicola', lastName: 'Bozikovic', club: 'Fighting Spirit Malmö', grade: 1 },
  { firstName: 'Linus', lastName: 'Andersen', club: 'Jönköping Kick- & Boxningsklubb', grade: 1 },
  { firstName: 'Martin', lastName: 'Johansson', club: 'Göteborgs Kickboxing', grade: 1 },
  { firstName: 'Isak', lastName: 'Lindmark', club: 'Göteborgs Kickboxing', grade: 1 },
  { firstName: 'Lee', lastName: 'Armano', club: 'Skurups Kick och boxningsklubb', grade: 1 },
  { firstName: 'Jennicka', lastName: 'Thomsen', club: 'Göteborgs Kickboxing', grade: 1 },
  { firstName: 'Pontus', lastName: 'Thor', club: 'Jönköpings Kickboxningsklubb', grade: 1 },
  { firstName: 'Melwin', lastName: 'Olsson', club: 'Furulunds Kickboxningsklubb', grade: 1 },

  // ─── 2 DAN ───────────────────────────────────────────────────────────────
  { firstName: 'Martin', lastName: 'Andersson', club: 'Sundsvall', grade: 2 },
  { firstName: 'Peter', lastName: 'Bodefjord', club: 'IMC', grade: 2 },
  { firstName: 'Remy', lastName: 'Brandefalk', club: 'Karlstad', grade: 2 },
  { firstName: 'Mikael', lastName: 'Cederhof', club: 'Payakaron', grade: 2 },
  { firstName: 'Henrik', lastName: 'Håkansson', club: 'FOX Malmö', grade: 2 },
  { firstName: 'Ulf', lastName: 'Håkansson', club: 'Lund', grade: 2 },
  { firstName: 'Martin', lastName: 'Hökros', club: 'Jönköping Kick- & Boxningsklubb', grade: 2 },
  { firstName: 'Mikael', lastName: 'Imhäuser', club: 'FOX Malmö', grade: 2 },
  { firstName: 'Stefan', lastName: 'Jacobsson', club: 'IMC', grade: 2 },
  { firstName: 'Fredrik', lastName: 'Jensen', club: 'Lund', grade: 2 },
  { firstName: 'Goran', lastName: 'Jovanovic', club: 'FOX Malmö', grade: 2 },
  { firstName: 'Håkan', lastName: 'Karlsson', club: 'IMC', grade: 2 },
  { firstName: 'Magnus', lastName: 'Kock', club: 'Stockholm', grade: 2 },
  { firstName: 'Perti', lastName: 'Kuronen', club: 'Finland', grade: 2 },
  { firstName: 'Robert', lastName: 'Lundmark', club: 'Göteborg', grade: 2 },
  { firstName: 'Publio', lastName: 'Mastrangelli', club: 'Enköping', grade: 2 },
  { firstName: 'Lars', lastName: 'Mårtensson', club: 'Skurup', grade: 2 },
  { firstName: 'Pierre', lastName: 'Palmberg', club: 'FOX Malmö', grade: 2 },
  { firstName: 'Ulla', lastName: 'Skrimsjö', club: 'Gotland', grade: 2 },
  { firstName: 'Robert', lastName: 'Stefansson/Sundin', club: 'IMC', grade: 2 },
  { firstName: 'Björn', lastName: 'Säljö', club: 'IMC', grade: 2 },
  { firstName: 'Raymond', lastName: 'Teibl', club: 'IMC', grade: 2 },
  { firstName: 'Rickard', lastName: 'Wadstedt', club: 'IMC', grade: 2 },
  { firstName: 'Linus', lastName: 'Grinsvall', club: 'Göteborgs Kickboxing', grade: 2 },
  { firstName: 'Dan', lastName: 'Hillpold', club: 'Fighting Spirit Kickboxningsklubb', grade: 2 },
  { firstName: 'Tony', lastName: 'Berglund', club: 'Landskrona Asiatiska Förening', grade: 2 },
  { firstName: 'Daniel', lastName: 'Hansson', club: 'Östersunds kampsportsförening', grade: 2 },
  { firstName: 'Jorma', lastName: 'Kiprianoff', club: 'IMC', grade: 2 },
  { firstName: 'Viktor', lastName: 'Nordh', club: 'IMC / Göteborgs Kickboxing', grade: 2 },

  // ─── 3 DAN ───────────────────────────────────────────────────────────────
  { firstName: 'Jonny', lastName: 'Gevrie', club: 'Göteborg', grade: 3 },
  { firstName: 'Rafael', lastName: 'Incze', club: 'FOX Malmö', grade: 3 },
  { firstName: 'Hannu', lastName: 'Kauppinen', club: 'Olofström', grade: 3 },
  { firstName: 'Alf', lastName: 'Lindgren', club: 'Payakaron', grade: 3 },
  { firstName: 'Mirek', lastName: 'Niedopad', club: 'FOX Malmö', grade: 3 },
  { firstName: 'Stefan', lastName: 'Oscarsson', club: 'IMC', grade: 3 },
  { firstName: 'Salah', lastName: 'Rahmouni', club: 'Göteborg', grade: 3 },
  { firstName: 'Leif', lastName: 'Roth', club: 'FOX Malmö', grade: 3 },
  { firstName: 'Dennis', lastName: 'Sigö', club: 'Helsingborg', grade: 3 },
  { firstName: 'Patrik', lastName: 'Sjöstrand', club: 'FOX Malmö', grade: 3 },
  { firstName: 'Patrik', lastName: 'Svensson', club: 'FOX Malmö', grade: 3 },
  { firstName: 'Krister', lastName: 'Ödhammar', club: 'FOX Malmö', grade: 3 },
  { firstName: 'Robert', lastName: 'de Zwart', club: 'Göteborgs Kickboxing', grade: 3 },
  { firstName: 'Rainer', lastName: 'Heinonen', club: 'IMC', grade: 3 },
  { firstName: 'Magnus', lastName: 'Segerberg', club: 'West Coast Kickboxing', grade: 3 },
  { firstName: 'Björn', lastName: 'Rhodin', club: 'West Coast Kickboxing', grade: 3 },
  { firstName: 'Sabrina', lastName: 'Sedin Rosenkvist', club: 'Fighting Spirit Malmö', grade: 3 },
  { firstName: 'Mikael', lastName: 'Bergh', club: 'Jönköping Kick- & Boxningsklubb', grade: 3 },

  // ─── 4 DAN ───────────────────────────────────────────────────────────────
  { firstName: 'Lars', lastName: 'Blomgren', club: 'Jönköping Kick- & Boxningsklubb', grade: 4 },
  { firstName: 'Thomas', lastName: 'Heiderup', club: 'Kalvhagen', grade: 4 },
  { firstName: 'Håkan', lastName: 'Ozan', club: 'Stockholm', grade: 4 },

  // ─── 5 DAN ───────────────────────────────────────────────────────────────
  { firstName: 'Jonny', lastName: 'Andreasson', club: 'IMC', grade: 5 },
  { firstName: 'Jyrki', lastName: 'Saario', club: 'IMC', grade: 5 },
  { firstName: 'Johan', lastName: 'Öjeheim', club: 'Jönköping Kick- & Boxningsklubb', grade: 5 },

  // ─── 6 DAN ───────────────────────────────────────────────────────────────
  { firstName: 'Benny', lastName: 'Hedlund', club: 'FOX Malmö', grade: 6 },
  { firstName: 'PO', lastName: 'Lindvall', club: 'Slagskeppet', grade: 6 },
];
